### ISSUE TITLE
Follow up from 07.28.2024

### ISSUE THREAD

**Issue by nniiicc** [JacksonMaxfield/phd#4]
A few things to follow up on: 
1. Create a summary of what we talked about today 
2. I mentioned the importance of formalizing some knowledge on writing, and research design. For the latter, I highly recommend the Declare Design method (https://book.declaredesign.org/). Happy to talk about any of these chapters at any time.

**Comment by evamaxfield** [comment]
# Meeting Notes and Follow Up

## How to Approach a Dissertation Proposal

### Two Options

1. Come with one paper and an idea of where you would like to go with your dissertation. But the idea must be backed up by heavy literature review and demonstration of knowledge.

2. Come with two, ideally three, papers already on the topic of your dissertation and discuss a major project (or two) that will tie existing work together and expand current capabilities of your work. Note: this still needs a strong literature review but the emphasis is on bringing completed work to show you have already progressed in the field.

### My Preference

In general, I side more towards option 2. That is, I hope to have a few more papers about (the science of) scientific software under my belt and I come with a major proposal in place which ties everything together and plans for larger work in the future.

I personally like this more because I want feedback on research I have already done and on specific areas my committee thinks I can expand into or help identify gaps I am missing. Further, from feedback at general exam, I simply need more practice in writing papers and I would like to have that practice before proposing my dissertation.

Fortunately we already have one paper in the works, with another not too far behind, and a third is possible.

## Current Work

### Papers in Progress

1. QSS paper on entity matching authors and github profiles -- minorly extended form of ICSSI presentation -- Note my goal on this is to have something submitted before Late Sept / October!

2. characterizing the sustainability patterns of scientific software -- write up of work done so far on EAGER, focusing on survey results, metrics regarding the creation of software per grant and per paper. linkage of said software, and most importantly, our understandings of the "four quadrants of scientific software sustainability" as it relates to the grant planning and application process.

3. rs-graph -- dataset of linked papers, code, authors, and developers, as well as network analysis identifying critical scientific software packages and developers. further expanding upon the QSS paper on entity matching authors and github profiles (1) to subset the network to author-developers and understand how developer-based network metrics align with author-based network metrics (centrality, h-index, etc.)

### Notes

@nniiicc requested I place these, and other, projects into a spreadsheet for tracking. The spreadsheet should include:

* the basic topic / premise of the work
* the main contributions (plainly laid out or rough sketches if still early)
* what are the current blockers / upstream dependencies for this work
* what is the venue / journal for a potential publication from the work

Treat this as a github issue for a feature request basically. What is the goal, why does it matter, who is affected, what are the upstreams, and what is the rough timeline

@nniiicc I will update this github issue with a link to a spreadsheet tomorrow (2024-08-06)!

## Literature Review / Survey Paper

We briefly talked about how we should write a literature review of "quantitative methods for researching scientific software" as part of my dissertation (both preparing for and during).

This would encompass finding and understand all of the ways that scientists have researched scientific software via quantitative means before, i.e.: scientific software datasets, scientific software review, scientific software measurement (growth, dissemination, use), developers of scientific software, etc.

I remember from prior conversations that I think we both lean towards "Systematic Literature Reviews" so coming up with an early idea of papers to seed our search with might be nice (i.e. to mine and generate keywords from to then pass to a pipeline for finding papers). I already have an ever-growing Semantic Scholar library of papers on the study of scientific software and I am sure you do as well but this also may be a really great place to reach and work with more collaborators as well.

## Writing Practices

I am trying to read and write more, and trying to come up with a way to systematize my writing (both via a new writing group that I am trying to go to on occasion but also just general everyday practice. We found the [Project-Paper-Template](https://docs.google.com/document/d/1KjNgiLUXO_jVuwTkTHp6wyBJr9KXHY2LJOyXowHkMCc/edit?usp=sharing) again to work from. Finally, thank you for the link to declare design! I will start to slowly read through it.

---

Let me know if you think I missed anything @nniiicc. I will also keep reading and thinking through things before our meeting on Wednesday as well as set up that project tracking system tomorrow!

**Comment by evamaxfield** [comment]
Link to very basic project-status spreadsheet: https://docs.google.com/spreadsheets/d/1YMa0f0TSClzDbVD2aDgDGze60SFp44NKScocLWjtOoE/edit?usp=sharing

**Comment by nniiicc** [comment]
Thanks, this is a good write-up. In the future - lets try to record basic topics covered and decisions. Any additional narrative or writing should be of use to you rather than something you have to do.  

To discuss later today: 
- https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-018-0611-x
